# permissions for end users to view kfpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: kfpipeline-controller
  name: kfpipeline-viewer-role
rules:
- apiGroups:
  - kfpipeline-controller.opendatahub.org
  resources:
  - kfpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kfpipeline-controller.opendatahub.org
  resources:
  - kfpipelines/status
  verbs:
  - get
