apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-auth-role
subjects:
- kind: ServiceAccount
  name: kfpipeline-controller-manager
  namespace: kfpipeline-controller
